name: ci
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up go 1.19
        uses: actions/set-up-go@v2
        with:
          go-version: 1.19
        id: go

      - name: Check out code into the Go modulo directory
        uses: actions/checkout@v2

      - name: Run test
        run: make test